blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogList, BlogCreate, BlogUpdate, BlogDetail, BlogDelete

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogList.as_view(), name='list_blog'),
    path('create/', BlogCreate.as_view(), name='create_blog'),
    path('update/<int:pk>', BlogUpdate.as_view(), name='update_blog'),
    path('detail/<int:pk>', BlogDetail.as_view(), name='detail_blog'),
    path('delete/<int:pk>', BlogDelete.as_view(), name='delete_blog'),
]

config/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailings.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('mailings.urls', namespace='mailing')),
                  path('users/', include('users.urls', namespace='users')),
                  path('blog/', include('blog.urls', namespace='blog')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailings/urls.py
from django.urls import path
from mailings.apps import MailingsConfig
from mailings.views import (HomeView, ClientsCreateView, ClientsUpdateView, ClientsListView, ClientsDeleteView,
                            MailingCreateView, MailingUpdateView, MailingDeleteView,
                            MessageCreateView, MailingListView, MessageUpdateView, MessageDeleteView,
                            MailingLogListView, MailingLogDetailView, MessageListView, MessageDetailView, toggle_active)

app_name = MailingsConfig.name

urlpatterns = [
    path('', HomeView.as_view(), name='home'),

    path('create-client/', ClientsCreateView.as_view(), name='create_client'),
    path('update-client/<int:pk>', ClientsUpdateView.as_view(), name='update_client'),
    path('list-client/', ClientsListView.as_view(), name='list_client'),
    path('delete-client/<int:pk>', ClientsDeleteView.as_view(), name='delete_client'),

    path('list-mailing/', MailingListView.as_view(), name='list_mailing'),
    path('creating-mailing/', MailingCreateView.as_view(), name='creating_mailing'),
    path('update-mailing/<int:pk>', MailingUpdateView.as_view(), name='update_mailing'),
    path('delete_mailing/<int:pk>', MailingDeleteView.as_view(), name='delete_mailing'),
    path('mailing/toggle_active/<int:pk>', toggle_active, name='toggle_active'),


    path('list-message/', MessageListView.as_view(), name='list_message'),
    path('create-message/', MessageCreateView.as_view(), name='create_message'),
    path('detail-message/<int:pk>', MessageDetailView.as_view(), name='detail_message'),
    path('update-message/<int:pk>', MessageUpdateView.as_view(), name='update_message'),
    path('delete-message/<int:pk>', MessageDeleteView.as_view(), name='delete_message'),

    path('list-log/', MailingLogListView.as_view(), name='list_log'),
    path('log-detail/<int:pk>', MailingLogDetailView.as_view(), name='detail_log'),
]

config/mailings/models.py
from django.db import models
from django.utils import timezone

from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Clients(models.Model):
    email = models.EmailField(unique=True, max_length=35, verbose_name='Почта')
    family_name = models.CharField(max_length=50, verbose_name='Фамилия')
    first_name = models.CharField(max_length=50, verbose_name='Имя')
    middle_name = models.CharField(max_length=50, verbose_name='Отчество', **NULLABLE)
    comment = models.TextField(verbose_name='Коммент', **NULLABLE)

    def __str__(self):
        return f'{self.email} '

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class Message(models.Model):
    title = models.CharField(max_length=100, verbose_name='Тема')
    message = models.TextField(verbose_name='Сообщение')
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, verbose_name='Пользователь', **NULLABLE)

    def __str__(self):
        return f'{self.title} {self.message}'


class Mailing(models.Model):
    list_period = (
        ('once_day', 'раз в день'),
        ('once_week', 'раз в неделю'),
        ('once_month', 'раз в месяц')
    )

    list_status = (
        ('created', 'создана'),
        ('executing', 'запущена'),
        ('finished', 'закончена успешно'),
        ('error', 'законечена с ошибками')
    )

    start_mailing = models.DateTimeField(default=timezone.now, verbose_name='Начало рассылки')
    next_mailing = models.DateTimeField(default=timezone.now, verbose_name='Следующая рассылка')
    end_mailing = models.DateTimeField(default=timezone.now, verbose_name='Конец рассылки', **NULLABLE)
    periodicity = models.CharField(max_length=100, choices=list_period, verbose_name='Периодичность')
    status = models.CharField(max_length=100, choices=list_status, verbose_name='Статус')

    clients = models.ForeignKey(Clients, on_delete=models.SET_NULL, verbose_name='Клиенты', **NULLABLE)
    message = models.ForeignKey(Message, on_delete=models.SET_NULL, verbose_name='Сообщение', **NULLABLE )
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, verbose_name='Пользователь', **NULLABLE)

    def __str__(self):
        return f'{self.owner} {self.start_mailing} {self.periodicity} {self.status}'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'


class Log_mailing(models.Model):
    ...

mailings/forms.py
from django.forms import ModelForm

from mailings.models import Message, Clients, Mailing


class StyleFormsMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class MessageForm(StyleFormsMixin, ModelForm):
    class Meta:
        model = Message
        exclude = ('owner',)


class ClientsForm(StyleFormsMixin, ModelForm):
    class Meta:
        model = Clients
        exclude = ('owner','is_active',)


class MailingForm(StyleFormsMixin, ModelForm):
    class Meta:
        model = Mailing
        exclude = ['owner', 'is_active',]

config/mailings/views.py
from django.shortcuts import render

# Create your views here.

mailings/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import TemplateView, CreateView, UpdateView, DeleteView, ListView, DetailView

from mailings.forms import MessageForm, ClientsForm, MailingForm
from mailings.models import Mailing, Message, Clients, MailingLog
from users.models import User


@login_required
def toggle_active(request, pk):
    """
    Функция переключения статуса
    """
    mailing = Mailing.objects.get(pk=pk)
    # Переключаем статус is_active, если только рассылка не завершена
    if mailing.status != 'finished':
        mailing.is_active = {mailing.is_active: False,
                             not mailing.is_active: True}[True]
        mailing.save()
    else:
        messages.error(request, 'Рассылка завершена')
    return redirect(reverse('mailing:list_mailing'))


class HomeView(TemplateView):
    template_name = 'mailings/home.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Главная'
        context_data['count_mailing'] = len(Mailing.objects.all())
        count_active_mailings = Mailing.objects.filter(is_active=True).count()
        context_data['count_active_mailings'] = count_active_mailings
        unique_clients_count = Clients.objects.filter(is_active=True).distinct().count()
        context_data['count_unique_clients'] = unique_clients_count
        # all_posts = list(Blog.objects.filter(is_published=True))
        # context_data['random_blog_posts'] = sample(all_posts, min(3, len(all_posts)))
        return context_data


# Контроллеры для клиента
class ClientsCreateView(LoginRequiredMixin, CreateView):
    model = Clients
    form_class = ClientsForm
    success_url = reverse_lazy('mailing:list_client')

    login_url = 'users:login'
    redirect_field_name = "redirect_to"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Добавление клиента'
        return context_data

    def form_valid(self, form):
        new_client = form.save()
        new_client.owner = self.request.user
        new_client.save()
        return super().form_valid(form)


class ClientsListView(ListView):
    model = Clients

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Клиенты'
        return context_data


class ClientsUpdateView(LoginRequiredMixin, UpdateView):
    model = Clients
    form_class = ClientsForm
    success_url = reverse_lazy('mailing:list_client')

    login_url = 'users:login'
    redirect_field_name = "redirect_to"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Редактирование клиента'
        return context_data

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.owner != self.request.user and not self.request.user.is_superuser:
            raise Http404
        return self.object


class ClientsDeleteView(LoginRequiredMixin, DeleteView):
    model = Clients
    success_url = reverse_lazy('mailing:list_client')

    login_url = 'users:login'
    redirect_field_name = "redirect_to"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Удаление пользователя'
        return context_data

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.owner != self.request.user and not self.request.user.is_superuser:
            raise Http404
        return self.object


# Контроллеры для рассылок
class MailingListView(LoginRequiredMixin, ListView):
    model = Mailing
    login_url = 'users:login'
    redirect_field_name = "redirect_to"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Рассылки'
        return context_data


class MailingCreateView(LoginRequiredMixin, CreateView):
    model = Mailing
    form_class = MailingForm
    login_url = 'users:login'
    redirect_field_name = "redirect_to"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Создать рассылку'
        return context_data

    def get_success_url(self):
        return reverse('mailing:list_mailing')

    def form_valid(self, form):
        new_mailing = form.save()
        new_mailing.owner = self.request.user
        new_mailing.save()
        return super().form_valid(form)


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailing:list_mailing')

    login_url = 'users:login'
    redirect_field_name = "redirect_to"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Обновить рассылку'
        return context_data


class MailingDeleteView(LoginRequiredMixin, DeleteView):
    model = Mailing
    success_url = reverse_lazy('mailing:list_mailing')

    login_url = 'users:login'
    redirect_field_name = "redirect_to"


# Контроллеры для сообщений
class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('mailing:list_message')

    login_url = 'users:login'
    redirect_field_name = "redirect_to"

    def form_valid(self, form):
        new_message = form.save()
        new_message.owner = self.request.user
        new_message.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Создание сообщения'
        return context_data


class MessageListView(LoginRequiredMixin, ListView):
    model = Message

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = f'Сообщения'
        return context_data


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('mailing:list_message')

    login_url = 'users:login'
    redirect_field_name = "redirect_to"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = f'Редактирование "{self.object.title}"'
        return context_data


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    success_url = reverse_lazy('mailing:list_message')

    login_url = 'users:login'
    redirect_field_name = "redirect_to"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Удаление сообщения'
        return context_data


class MessageDetailView(LoginRequiredMixin, DetailView):
    model = Message
    login_url = 'users:login'
    redirect_field_name = "redirect_to"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Детали сообщения'
        return context_data


# Контроллеры для логов рассылок
class MailingLogListView(LoginRequiredMixin, ListView):
    model = MailingLog
    login_url = 'users:login'
    redirect_field_name = "redirect_to"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = f'Логи'
        return context_data


class MailingLogDetailView(LoginRequiredMixin, DetailView):
    model = MailingLog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user and not self.request.user.is_superuser:
            raise Http404
        return self.object

mailings/templates/mailings/base.html
<!doctype html>
<html lang="ru">

{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<div class="container">
    {% include 'mailings/includes/inc_title.html' %}

    {% block content %}
    {% endblock %}
</div>

<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md">
                <small class="d-block mb-3 text-muted">&copy; {% now 'Y' %}</small>
            </div>
        </div>
    </div>
</footer>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

mailings/templates/mailings/clients_form.html
{% extends 'mailings/base.html' %}
{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-6">
            {% if object %}
                Редактирование "{{ object }}"
            {% else %}
                Добавление клиента
            {% endif %}
        </h1>
    </div>

    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

mailings/templates/mailings/clients_list.html
{% extends 'mailings/base.html' %}
{% load my_tags %}
{% block content %}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h3>Клиенты</h3>
    <div class="btn-toolbar mb-2 mb-md-0">
        <a type="button" class="btn btn-sm btn-secondary" href="{% url 'mailing:create_client' %}">Добавить</a>
    </div>
</div>

<div class="table-responsive small">
    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th>Имя</th>
            <th>Фамилия</th>
            <th>Отчество</th>
            <th>E-mail</th>
            {% if request.user.is_superuser %}
            <th>Создал</th>
            {% endif %}
        </tr>
        </thead>
        {% for object in object_list %}
        <tr>

            <td>{{ object.first_name }}</td>
            <td>{{ object.family_name }}</td>
            <td>{{ object.middle_name }}</td>
            <td>{{ object.email }}
            </td>
            {% if request.user.is_superuser %}
            <td>{{ object.owner }}</td>
            {% endif %}
            <td>
                {% if request.user|has_group:2 or request.user == object.owner or request.user.is_superuser %}
                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                    <a type="button" class="btn" href="{% url 'mailing:update_client' object.pk %}"
                       style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">
                        Обновить
                    </a>
                    <a type="button" class="btn" href="{% url 'mailing:delete_client' object.pk %}"
                       style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">
                        Удалить
                    </a>
                </div>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

mailings/templates/mailings/mailing_confirm_delete.html
{% extends 'mailings/base.html' %}
{% block content %}


    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-6">
            Удаление рассылки
        </h1>
    </div>

    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить "{{ object }}"?</p>
                        <button type="submit" class="btn btn-danger">
                            Подтвердить
                        </button>
                        <a href="{% url 'mailing:list_mailing' %}" class="btn btn-primary">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

mailings/templates/mailings/mailing_list.html
{% extends 'mailings/base.html' %}
{% block content %}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h3>Рассылки</h3>
    <div class="btn-toolbar mb-2 mb-md-0">
        <a type="button" class="btn btn-sm btn-secondary mx-1" href="{% url 'mailing:list_log' %}">Логи</a>
        <a type="button" class="btn btn-sm btn-secondary" href="{% url 'mailing:creating_mailing' %}">Добавить
            рассылку</a>
    </div>
</div>

<div class="table-responsive small">
    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th>Начало рассылки</th>
            <th>Следующая рассылка</th>
            <th>Окончание рассылки</th>
            <th>Периодичность</th>
            <th>Тема сообщения</th>
            <th>Статус</th>
            {% if user.is_superuser %}
            <th>Создал</th>
            {% endif %}
            <th>Возможности</th>
        </tr>
        </thead>

        {% for object in object_list %}
        <tr>
            <td>{{ object.start_mailing|date:"d M Y" }}</td>
            <td>{{ object.next_mailing|date:"d M Y" }}</td>
            <td>{{ object.end_mailing|date:"d M Y" }}</td>


            {% if object.periodicity == 'once_day' %}
            <td>Ежедневно в {{ object.start_mailing|time:"H:i" }}</td>
            {% elif object.periodicity == "once_week" %}
            <td>Еженедельно {{ object.start_mailing|date:"d M Y" }} at {{ object.start_mailing|time:"H:i" }}</td>
            {% elif object.periodic == 'once_month' %}
            <td>Ежемесячно {{ object.start_mailing}} day at {{ object.start_mailing|time:"H:i" }}</td>
            {% endif %}

            <td>{{ object.message.title|truncatechars:20 }}</td>

            {% if object.is_active %}
                {% if object.status == 'created' %}
                <td>Создана</td>
                {% elif object.status == 'executing' %}
                <td>Запущена</td>
                {% elif object.status == 'finished' %}
                <td>Окончена</td>
                {% elif object.status == 'error' %}
                <td>Ошибка сервера</td>
                {% endif %}
            {% endif %}

            <td>
                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                    <a type="button" class="btn" href="{% url 'mailing:toggle_active' object.pk %}"
                       style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .25rem; --bs-btn-font-size: .75rem;">
                        {% if object.status != 'finished' and 'error' %}
                        {% if object.is_active %}
                        Отключить
                        {% else %}
                        Включить
                        {% endif %}
                        {% endif %}
                    </a>

                    <a type="button" class="btn"
                       href="{% url 'mailing:update_mailing' object.pk %}"
                       style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .25rem; --bs-btn-font-size: .75rem;">
                        Обновить
                    </a>
                    <a type="button" class="btn"
                       href="{% url 'mailing:delete_mailing' object.pk %}"
                       style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .25rem; --bs-btn-font-size: .75rem;">
                       Удалить
                    </a>
                </div>
            </td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

mailings/templates/mailings/mailinglog_list.html
{% extends 'mailings/base.html' %}
{% block content %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h3>Логи</h3>
</div>
<div class="table-responsive small">
    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th>Дата</th>
            <th>Статус</th>
            <th>Периодичность рассылки</th>
            <th>Ответ сервера</th>

            <th>
                <div class="d-grid gap-2 d-md-flex justify-content-md-end">Action</div>
            </th>
        </tr>
        </thead>

        {% for object in object_list %}
        <tr>
            <td>{{ object.last_attempt|date:"d M Y H:i" }}</td>
            <td>
                {% if object.status %}
                <span class="badge rounded-pill text-bg-success">Упешно</span>
                {% else %}
                <span class="badge rounded-pill text-bg-danger">Ошибка отправления</span>
                {% endif %}
            </td>
            <td>{{ object.mailing.periodicity|truncatechars:50 }}</td>
            <td>{{ object.server_response|truncatechars:50 }}</td>
            <td>
                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                    <a type="button" class="btn" href="{% url 'mailing:detail_log' object.pk %}"
                       style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">
                        Подробнее
                    </a>
                </div>
            </td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

mailings/templates/mailings/message_confirm_delete.html
{% extends 'mailings/base.html' %}
{% block content %}


<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">
        Удаление сообщения
    </h1>
</div>

<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <p>Хотите удалить "{{ object }}"?</p>
                    <button type="submit" class="btn btn-danger">
                        Подтвердить
                    </button>
                    <a href="{% url 'mailing:detail_message' object.pk %}" class="btn btn-primary">Отмена</a>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mailings/templates/mailings/message_detail.html
{% extends 'mailings/base.html' %}
{% block content %}


    <div class="card">
        <div class="row">
            <div class="card-header">
                <p><h4 class="card-title"><strong>{{ object.title }}</strong></h4>
            </div>
            <div class="col">
                <div class="card-body">
                    <div class="container-fluid">
                        <dl class="row">
                            <dt class="col-sm-2">Тема сообщения:</dt>
                            <dd class="col-sm-10">{{ object.title }}</dd>
                        </dl>
                        <dl class="row">
                            <dt class="col-sm-2">Текст сообщения:</dt>
                            <dd class="col-sm-10">{{ object.message|linebreaksbr }}</dd>
                        </dl>
                    </div>
                </div>
            </div>
            <style>
                .raz {
                    text-align: right;
                }
            </style>
            <div class="card-footer">
                <div class="d-flex justify-content-between align-items-center">
                    <small>Создано: <strong>{{ object.created_at|date:"d M Y H:i:s" }}</strong>, Обновлено:
                        <strong>{{ object.modified_date|date:"d M Y H:i:s" }}</strong></small>
                    <div class="btn-group">
                        <a class="btn btn-sm btn-outline-primary"
                           href="{% url 'mailing:update_message' object.pk %}">Редактировать</a>
                        <a class="btn btn-outline-danger btn-sm"
                           href="{% url 'mailing:delete_message' object.pk %}">Удалить</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

mailings/templates/mailings/message_list.html
{% extends 'mailings/base.html' %}
{% load my_tags %}
{% block content %}


<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h3>Сообщения</h3>
    <div class="btn-toolbar mb-2 mb-md-0">
        <a type="button" class="btn btn-sm btn-secondary" href="{% url 'mailing:create_message' %}">Создать
            сообщение</a>
    </div>
</div>

<div class="table-responsive small">
    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th>Тема сообщения</th>
            <th>Сообщение</th>
            {% if request.user.is_superuser or request.user == object.owner %}
            <th>Создал</th>
            {% endif %}
            <th>
                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                    Возможности
                </div>
            </th>
        </tr>
        </thead>

        {% for object in object_list %}
        <tr>
            <td>{{ object.title|truncatechars:20 }}</td>
            <td>{{ object.message|truncatechars:25 }}</td>
            {% if request.user.is_superuser %}
            <td>{{ object.owner }}</td>
            {% endif %}

            {% if request.user|has_group:2 or request.user == object.owner or request.user.is_superuser %}
            <td>
                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                    <a type="button" class="btn" href="{% url 'mailing:detail_message' object.pk %}"
                       style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .25rem; --bs-btn-font-size: .75rem;">
                        Просмотреть
                    </a>
                    <a type="button" class="btn" href="{% url 'mailing:update_message' object.pk %}"
                       style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .25rem; --bs-btn-font-size: .75rem;">
                        Обновить
                    </a>
                    <a type="button" class="btn" href="{% url 'mailing:delete_message' object.pk %}"
                       style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .25rem; --bs-btn-font-size: .75rem;">
                        Удалить
                    </a>
                </div>
            </td>
            {% endif %}
        </tr>
        {% endfor %}
    </table>
</div>

{% endblock %}