blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogList, BlogCreate, BlogUpdate, BlogDetail, BlogDelete

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogList.as_view(), name='list_blog'),
    path('create/', BlogCreate.as_view(), name='create_blog'),
    path('update/<int:pk>', BlogUpdate.as_view(), name='update_blog'),
    path('detail/<int:pk>', BlogDetail.as_view(), name='detail_blog'),
    path('delete/<int:pk>', BlogDelete.as_view(), name='delete_blog'),
]

config/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailings.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('mailings.urls', namespace='mailing')),
                  path('users/', include('users.urls', namespace='users')),
                  path('blog/', include('blog.urls', namespace='blog')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='Заголовок')
    slug = models.CharField(max_length=150, verbose_name='slug', null=True, blank=True)
    text = models.TextField(verbose_name='Содержимое')
    image = models.ImageField(upload_to='blog', verbose_name='Превью', null=True, blank=True)
    data_created = models.DateField(verbose_name='Дата создания', auto_now=True)
    is_published = models.BooleanField(verbose_name='Опубликовано', default=False)
    views_count = models.IntegerField(default=0, verbose_name='Просмотры')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'статья'
        verbose_name_plural = 'статьи'

blog/forms.py
from django.forms import ModelForm

from blog.models import Blog


class StyleFormsMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if field_name == 'is_published':
                field.widget.attrs['class'] = 'switch'


class BlogForm(StyleFormsMixin, ModelForm):
    class Meta:
        model = Blog
        fields = ('title', 'text', 'image')


class BlogUpdateForm(StyleFormsMixin, ModelForm):
    class Meta:
        model = Blog
        fields = ('title', 'text', 'image', 'is_published')

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse_lazy
from django.utils.text import slugify
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView

from blog.forms import BlogForm, BlogUpdateForm
from blog.models import Blog


class BlogList(ListView):
    model = Blog

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['title'] = 'Список статей'
        return context_data


class BlogCreate(LoginRequiredMixin, CreateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('blog:list_blog')

    login_url = 'users:login'
    redirect_field_name = "redirect_to"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Создание статьи'
        return context_data

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)


class BlogUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Blog
    form_class = BlogUpdateForm
    success_url = reverse_lazy('blog:list_blog')
    permission_required = 'update_blog'

    login_url = 'users:login'
    redirect_field_name = "redirect_to"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Редактировать статью'
        return context_data

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)


class BlogDetail(DetailView):
    model = Blog
    fields = ('title', 'text', 'image', )
    success_url = reverse_lazy('blog:list_blog')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'О статье'
        return context_data

    def get_object(self, queryset=None):
        """Счетчик просмотров"""
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:list_blog')
    permission_required = 'delete_blog'

    login_url = 'users:login'
    redirect_field_name = "redirect_to"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Удалить статью'
        return context_data

blog/templates/blog/blog_confirm_delete.html
{% extends 'mailings/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">
        Удаление новости
    </h1>
</div>
<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <p>Хотите удалить "{{object.title}}"?</p>
                    <button type="submit" class="btn btn-danger">
                        Подтвердить
                    </button>
                    <a href="{% url 'blog:list' %}" class="btn btn-primary">Отмена</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'mailings/base.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-6" >{{ object.title }}</h1>
</div>

<div class="row">
    <div class="col-4">
        <div class="row text-start">
            <img style='height: 200px; width: 350px; object-fit: contain' alt="Image"
                 onerror="this.src='https://img.razrisyika.ru/img/173/1200/689342-blestyaschaya-raskraska-novosti-stranicy.jpg'"
                 src="{{ object.image|mediapath }}"/>
        </div>
    </div>
    <div class="col-8">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <p>
                    {{ object.text }}
                </p>
                {% if perms.blog.change_blog %}
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="{% url 'blog:update_blog' object.pk %}"
                           class="btn btn-sm btn-outline-primary">Редактировать</a>
                        <a href="{% url 'blog:delete_blog' object.pk %}"
                           class="btn btn-sm btn-outline-danger">Удалить</a>
                    </div>
                </div>
                {% endif %}
            </div>
            <div class="card-footer">
                <div class="d-flex justify-content-between align-items-center">
                    <small>Создано: <strong>{{ object.data_created }}</strong></small>
                    <div class="ml-auto">
                        Просмотры: {{ object.views_count }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'mailings/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center"></div>

<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'mailings/base.html' %}
{% load my_tags %}

{% block content %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h3>Блог</h3>
    <div class="btn-toolbar mb-2 mb-md-0">
        <a type="button" class="btn btn-sm btn-secondary" href="{% url 'blog:create_blog' %}">Создать запись</a>
    </div>
</div>
<div class="row text-center">
    {% for object in object_list %}
    {% if object.is_published %}
    <div class="col-4">
        <div class="card mb-4 box-shadow">
            <img class="rounded form-control"
                 style='width: 300px;height: 300px;overflow: hidden;margin: 20px; object-fit: contain'
                 alt="Image"
                 onerror="this.src='https://img.razrisyika.ru/img/173/1200/689342-blestyaschaya-raskraska-novosti-stranicy.jpg'"
                 src="{% mediapath object.image %}"/>
            <div class="card-body">
                <h3 class="card-title pricing-card-title">{{ object.title|truncatechars:30 }}</h3>
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    <p>{{ object.text|truncatechars:100 }}</p>
                </ul>
                <a href="{% url 'blog:detail_blog' object.pk %}" type="button"
                   class="btn btn-primary btn-block btn-outline-dark mt-auto">Подробнее</a>
            </div>
        </div>
    </div>
    {% else %}
    {% if perms.update_blog or request.user.is_superuser %}
    <div class="col-4">
        <div class="card mb-4 box-shadow">
            <img class="rounded form-control"
                 style='width: 300px;height: 300px;overflow: hidden;margin: 20px; object-fit: contain'
                 alt="Image"
                 onerror="this.src='https://img.razrisyika.ru/img/173/1200/689342-blestyaschaya-raskraska-novosti-stranicy.jpg'"
                 src="{% mediapath object.image %}"/>
            <div class="card-body">
                <h3 class="card-title pricing-card-title">{{ object.title }}</h3>
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    <p>{{ object.text|truncatechars:100 }}</p>
                </ul>
                <a href="{% url 'blog:detail_blog' object.pk %}" type="button"
                   class="btn btn-primary btn-block btn-outline-dark mt-auto">Подробнее</a>
                <a href="{% url 'blog:update_blog' object.pk %}" type="button"
                   class="btn btn-primary btn-block btn-warning mt-1">Опубликовать</a>
            </div>
        </div>
    </div>
    {% endif %}
    {% endif %}
    {% empty %}
    <p>Нет записей.</p>
    {% endfor %}
</div>
{% endblock %}