blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogList, BlogCreate, BlogUpdate, BlogDetail, BlogDelete

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogList.as_view(), name='list_blog'),
    path('create/', BlogCreate.as_view(), name='create_blog'),
    path('update/<int:pk>', BlogUpdate.as_view(), name='update_blog'),
    path('detail/<int:pk>', BlogDetail.as_view(), name='detail_blog'),
    path('delete/<int:pk>', BlogDelete.as_view(), name='delete_blog'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('mailings.urls', namespace='mailing')),
                  path('users/', include('users.urls', namespace='users')),
                  path('blog/', include('blog.urls', namespace='blog')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/users/urls.py
from django.urls import path
from users.apps import UsersConfig

app_name = UsersConfig.name

urlpatterns = [

]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import (UserRegisterView, UserDetailView, UserUpdateView, GeneratePasswordView, email_verification,
                         UserListView, block_user)

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('register/', UserRegisterView.as_view(), name='register'),
    path('update/', UserUpdateView.as_view(), name='update'),
    path('profile/', UserDetailView.as_view(), name='profile'),
    path('email.confirm/<str:verification_code>/', email_verification, name='email_verification'),
    path('reset_pass', GeneratePasswordView.as_view(template_name='users/reset_password.html'), name='reset_pass'),

    path('list/', UserListView.as_view(), name='list_users'),
    path('block_user/<int:pk>', block_user, name='block_user')
]

config/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {"blank": True, "null": True}


class User(AbstractUser):
    username = None

    email = models.EmailField(unique=True, max_length=35, verbose_name='Почта')
    avatar = models.ImageField(upload_to='users/avatars', verbose_name='Аватар', **NULLABLE)
    num_phone = models.CharField(unique=True, max_length=35, verbose_name='Телефон', **NULLABLE)
    country = models.CharField(verbose_name='Страна', **NULLABLE)

    verification_code = models.CharField(max_length=100, verbose_name='Код подтверждения', **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return f"{self.email} "

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.safestring import mark_safe

NULLABLE = {"blank": True, "null": True}


class User(AbstractUser):
    username = None

    email = models.EmailField(unique=True, max_length=35, verbose_name='Почта')
    avatar = models.ImageField(upload_to='users/avatars', default='users/avatars/default_avatar.jpg', verbose_name='Аватар', **NULLABLE)
    num_phone = models.CharField(unique=True, max_length=35, verbose_name='Телефон', **NULLABLE)
    country = models.CharField(verbose_name='Страна', **NULLABLE)

    verification_code = models.CharField(max_length=100, verbose_name='Код подтверждения', **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def image_tag(self):
        if self.avatar:
            return mark_safe(f'<img src="{object.avatar}" style="width: 45px; height:45px;" />' % self.avatar)
        else:
            return 'No Image Found'

    image_tag.short_description = 'Image'

    def __str__(self):
        return f"{self.email} "

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from mailings.forms import StyleFormsMixin

from users.models import User


class RegisterForm(StyleFormsMixin, UserCreationForm):

    class Meta:
        model = User
        fields = ['email', 'password1', 'password2']

    def label_from_instance(self, obj):
        # Переводим поля формы на русский язык
        if self.fields['password1']:
            self.fields['password1'].label = 'Пароль'
        if self.fields['password2']:
            self.fields['password2'].label = 'Подтверждение пароля'

        return super().label_from_instance(obj)


class UpdateForm(StyleFormsMixin, UserChangeForm):

    # password1 = forms.CharField(label='Новый пароль', widget=forms.PasswordInput)
    # password2 = forms.CharField(label='Повторите новый пароль', widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'num_phone', 'avatar', 'country']

    # def clean_password1(self):
    #     # Получаем первый пароль
    #     password1 = self.cleaned_data.get("password1")
    #     # Получаем второй пароль
    #     password2 = self.cleaned_data.get("password2")
    #     # Проверяем, что оба пароля совпадают
    #     if password1 and password2 and password1 != password2:
    #         raise forms.ValidationError("Пароли должны совпадать.")
    #     return password2

config/users/views.py
from django.shortcuts import render

# Create your views here.

users/views.py
import secrets

from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.views import PasswordResetView
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, DetailView, ListView

from config.settings import EMAIL_HOST_USER
from users.forms import RegisterForm, UpdateForm
from users.models import User


class UserListView(PermissionRequiredMixin, ListView):
    model = User
    permission_required = 'users.view_user'
    template_name = 'users/users_list.html'

    def get_queryset(self, *args, **kwargs):
        if self.request.user.is_superuser:
            queryset = super().get_queryset()
        else:
            queryset = super().get_queryset().filter(is_superuser=False, is_staff=False)
        return queryset


@permission_required('users.view_user')
def block_user(self, pk):
    user = User.objects.get(pk=pk)
    user.is_active = {user.is_active: False,
                      not user.is_active: True}[True]
    user.save()
    return redirect(reverse('users:list_users'))


class UserRegisterView(CreateView):
    model = User
    form_class = RegisterForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/register.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Регистрация аккаунта'
        return context_data

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        user.set_password(user.password)
        verification_code = secrets.token_hex(16)
        user.verification_code = verification_code
        user.save()
        host = self.request.get_host()
        url = f'http://{host}/users/email.confirm/{verification_code}'
        send_mail(
            subject='Подтверждение почты',
            message=f'Для подтверждения почты перейдите по ссылке: {url}',
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email],
        )
        user.save()
        return super().form_valid(form)


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Профиль'
        return context_data


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UpdateForm
    success_url = reverse_lazy('users:profile')

    def form_valid(self, form):
        # Сохраняем новый пароль
        user = form.save(commit=False)
        user.set_password(form.cleaned_data["password1"])
        user.save()

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Редактировать профиль'
        return context_data

    def get_object(self, queryset=None):
        return self.request.user


def email_verification(request, verification_code):
    user = get_object_or_404(User, verification_code=verification_code)
    if user:
        user.is_active = True
        user.verification_code = None
        user.save()
        return redirect(reverse("users:login"))


class GeneratePasswordView(PasswordResetView):
    form_class = PasswordResetForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        if form.is_valid():
            email = form.cleaned_data['email']
            try:
                user = User.objects.get(email=email)
                password = User.objects.make_random_password(length=8)
                user.set_password(password)
                user.save()
                send_mail(
                    'Смена пароля',
                    f'Здравствуйте.Вы запросили генерацию нового пароля для локального сайта. '
                    f'Ваш новый пароль: {password}',
                    from_email=EMAIL_HOST_USER,
                    recipient_list=[user.email],
                )
                return redirect(reverse("users:login"))
            except User.DoesNotExist:
                messages.error(self.request, "Такого пользователя не существует.")
                return redirect(reverse("users:reset_password"))
        else:
            messages.error(self.request, "Произошла ошибка при генерации пароля.")
            return super().form_invalid(form)

users/templates/users/login.html
{% extends 'mailings/base.html' %}

{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-6">Авторизация</h1>
    </div>
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header"></div>
                <div class="card-body">
                    <form method="post">
                        <div class="d-grid gap-2 col-8 mx-auto">
                            {% csrf_token %}
                            {{ form.as_p }}
                        </div>
                        <div class="d-grid gap-2 col-4 mx-auto">
                            <button type="submit" class="btn btn-outline-dark">Войти</button>
                        </div>
                    </form>
                </div>
                <div class="card-footer">
                    <a href="{% url 'users:reset_pass' %}">Забыли пароль?</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-6">Регистрация</h1>
</div>
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h5>
                    <span class="text-danger">Вам будет отправлено письмо для потверждения аккаунта,
                    перейдите по ссылке указаной в сообщении
                    </span>
                </h5>
            </div>
            <div class="card-body">
                <form method="post" action="{% url 'users:register' %}">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="d-grid gap-2 col-6 mx-auto">
                        <button type="submit" class="btn btn-outline-dark">Зарегистрироваться</button>
                    </div>
                </form>
            </div>
            <div class="card-footer"></div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/reset_password.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-6">Восстановление пароля</h1>
</div>
<div class="row justify-content-center">
    <div class="col-6">
        <div class="card">
            <form method="post" enctype="multipart/form-data">
                <div class="d-grid gap-2 col-5 mx-auto mt-5">
                    {% csrf_token %}
                    {{ form.as_p }}
                </div>
                <div class="card-footer">
                    <div class="d-grid gap-2 col-7 mx-auto ">
                    <button type="submit" class="btn btn-dark mt-2 ">Восстановить пароль</button>
                </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_detail.html
{% extends 'mailings/base.html' %}

{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h2 class="display-10">Профиль</h2>
    </div>
    <div class="row">
        <div class="col-2"></div>
        <div class="col-8">
            <div class="card">
                <div class="card-header"></div>
                <div class="card-body">
                    <div class="col-8">
                        <p><strong>Почта:</strong> {{ object.email }}</p>
                        {% if object.first_name %}
                            <p><strong>Имя:</strong> {{ object.first_name }}</p>
                        {% endif %}

                        {% if object.last_name %}
                            <p><strong>Фамилия:</strong> {{ object.last_name }}</p>
                        {% endif %}

                        {% if object.country %}
                            <p><strong>Страна:</strong> {{ object.country }}</p>
                        {% endif %}

                        {% if object.num_phone %}
                            <p><strong>Phone:</strong> {{ object.num_phone }}</p>
                        {% endif %}
                    </div>
                    <div class="col-4">
                        {#object.avatar#}
                    </div>
                </div>
            </div>
            <div class="card-footer justify-content-end">
                <a class="btn btn-outline-dark" href="{% url 'users:update' %}">Редактировать</a>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'mailings/base.html' %}
{% block content %}


<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-6">Редактирование профиля</h1>
</div>
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header"></div>
            <form method="post" enctype="multipart/form-data">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-outline-success">Сохранить</button>
                    <button type="button" class="btn btn-danger" href="{% url 'users:profile' %}">Отмена</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/users_list.html
{% extends 'mailings/base.html' %}
{% load my_tags %}
{% block content %}

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h3>Пользователи</h3>
    </div>

    <div class="table-responsive small">
        <table class="table table-striped table-hover">
            <thead>
            <tr>
                <th>Email</th>
                <th>Имя</th>
                <th>Фамилия</th>
                <th>Возможности</th>
            </tr>
            </thead>

            {% for object in object_list %}

                <tr>
                    <td>{{ object.email }}</td>
                    <td>{{ object.first_name }}</td>
                    <td>{{ object.last_name }}</td>

                    <td>
                        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                            {% if object.is_active %}
                                <a type="button" class="btn btn-danger form-control"
                                   href="{% url 'users:block_user' object.pk %}">Заблокировать</a>
                            {% else %}
                                <a type="button" class="btn btn-success form-control"
                                   href="{% url 'users:block_user' object.pk %}">Разблокировать</a>
                            {% endif %}
                        </div>
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}